version: '3.1'

services:

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: "123456"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
